const categorysActionTypes = {
    GET_CATEGORYS_REQUEST: 'GET_CATEGORYS_REQUEST',
    GET_CATEGORYS_SUCCESS: 'GET_CATEGORYS_SUCCESS',
    GET_CATEGORYS_ERROR: 'GET_CATEGORYS_ERROR',

    GET_PRODUCT_TYPES_REQUEST: 'GET_PRODUCT_TYPES_REQUEST',
    GET_PRODUCT_TYPES_SUCCESS: 'GET_PRODUCT_TYPES_SUCCESS',
    GET_PRODUCT_TYPES_ERROR: 'GET_PRODUCT_TYPES_ERROR',

    CREATE_PRODUCT_TYPE_START: 'CREATE_PRODUCT_TYPE_START',
    CREATE_PRODUCT_TYPE_SUCCESS: 'CREATE_PRODUCT_TYPE_SUCCESS',
    CREATE_PRODUCT_TYPE_ERROR: 'CREATE_PRODUCT_TYPE_ERROR',

    CREATE_CATEGORY_START: 'CREATE_CATEGORY_START',
    CREATE_CATEGORY_SUCCESS: 'CREATE_CATEGORY_SUCCESS',
    CREATE_CATEGORY_ERROR: 'CREATE_CATEGORY_ERROR',

    GET_SUB_CATEGORYS_START: 'GET_SUB_CATEGORYS_START',
    GET_SUB_CATEGORYS_SUCCESS: 'GET_SUB_CATEGORYS_SUCCESS',
    GET_SUB_CATEGORYS_ERROR: 'GET_SUB_CATEGORYS_ERROR',

    CREATE_SUB_CATEGORY_START: 'CREATE_SUB_CATEGORY_START',
    CREATE_SUB_CATEGORY_SUCCESS: 'CREATE_SUB_CATEGORY_SUCCESS',
    CREATE_SUB_CATEGORY_ERROR: 'CREATE_SUB_CATEGORY_ERROR',
};

export default categorysActionTypes;