const productsActionsTypes = {
    GET_PRODUCTS_START : 'GET_PRODUCTS_START',
    GET_PRODUCTS_SUCCESS : 'GET_PRODUCTS_SUCCESS',
    GET_PRODUCTS_ERROR : 'GET_PRODUCTS_ERROR',

    CREATE_PRODUCT_START : 'CREATE_PRODUCT_START',
    CREATE_PRODUCT_SUCCESS : 'CREATE_PRODUCT_SUCCESS',
    CREATE_PRODUCT_ERROR : 'CREATE_PRODUCT_ERROR',

    DELETE_PRODUCT_START : 'DELETE_PRODUCT_START',
    DELETE_PRODUCT_SUCCESS : 'DELETE_PRODUCT_SUCCESS',
    DELETE_PRODUCT_ERROR : 'DELETE_PRODUCT_ERROR',
}

export default productsActionsTypes