const usersActionsTypes = {
    GET_CURRENT_USER_START: 'GET_CURRENT_USER_START',
    GET_CURRENT_USER_ERROR: 'GET_CURRENT_USER_ERROR',
    GET_CURRENT_USER_SUCCESS: 'GET_CURRENT_USER_SUCCESS',

    LOGIN_START: 'LOGIN_START',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_ERROR: 'LOGIN_ERROR'
};

export default usersActionsTypes;